package com.zhjie.knowledgeBank.dao;

import com.zhjie.knowledgeBank.entity.KnowledgeInfo;

public interface KnowledgeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_info
     *
     * @mbggenerated
     */
    int insert(KnowledgeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_info
     *
     * @mbggenerated
     */
    int insertSelective(KnowledgeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_info
     *
     * @mbggenerated
     */
    KnowledgeInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(KnowledgeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_knowledge_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(KnowledgeInfo record);
}